services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
    command: start-dev
    networks:
      - finmon-network
    volumes:
      - keycloak-data:/opt/keycloak/data
      - keycloak-logs:/opt/keycloak/logs

networks:
  finmon-network:
    name: finmon-network

volumes:
  keycloak-data:
  keycloak-logs:

#keycloak:
#  build:
#    context: ./data
#    dockerfile: Dockerfile.kc
#  restart: always
#  ports:
#    - '8080:8080'
#  networks:
#    - mapzilla-network
#  environment:
#    - KEYCLOAK_ADMIN=admin
#    - KEYCLOAK_ADMIN_PASSWORD=admin
#    - KC_HOSTNAME=localhost
#    - KC_HTTP_PORT=8080
